export const circuits = {
	/** Mulitple wires connected together at one central handle */
	multiconnected:
		'{"components":{"0":{"type":"AND","size":{"x":4,"y":4},"position":{"x":80,"y":240},"handles":{"in1":{"edge":"left","pos":1,"type":"input","connections":[]},"in2":{"edge":"left","pos":3,"type":"input","connections":[]},"out":{"edge":"right","pos":2,"type":"output","connections":[]}},"isPoweredInitially":false,"id":0},"1":{"type":"AND","size":{"x":4,"y":4},"position":{"x":340,"y":280},"handles":{"in1":{"edge":"left","pos":1,"type":"input","connections":[{"id":2,"handleType":"output"}]},"in2":{"edge":"left","pos":3,"type":"input","connections":[{"id":9,"handleType":"output"}]},"out":{"edge":"right","pos":2,"type":"output","connections":[]}},"isPoweredInitially":false,"id":1},"4":{"type":"AND","size":{"x":4,"y":4},"position":{"x":80,"y":80},"handles":{"in1":{"edge":"left","pos":1,"type":"input","connections":[]},"in2":{"edge":"left","pos":3,"type":"input","connections":[]},"out":{"edge":"right","pos":2,"type":"output","connections":[{"id":8,"handleType":"input"}]}},"isPoweredInitially":false,"id":4},"5":{"type":"AND","size":{"x":4,"y":4},"position":{"x":320,"y":80},"handles":{"in1":{"edge":"left","pos":1,"type":"input","connections":[{"id":6,"handleType":"output"}]},"in2":{"edge":"left","pos":3,"type":"input","connections":[{"id":7,"handleType":"output"}]},"out":{"edge":"right","pos":2,"type":"output","connections":[]}},"isPoweredInitially":false,"id":5}},"wires":{"2":{"input":{"x":240,"y":220,"connections":[{"id":8,"handleType":"output"}]},"output":{"x":340,"y":300,"connections":[{"id":1,"handleId":"in1"}]},"id":2},"6":{"input":{"x":240,"y":220,"connections":[{"id":8,"handleType":"output"}]},"output":{"x":320,"y":100,"connections":[{"id":5,"handleId":"in1"}]},"id":6},"7":{"input":{"x":240,"y":220,"connections":[{"handleType":"output","id":8}]},"output":{"x":320,"y":140,"connections":[{"id":5,"handleId":"in2"}]},"id":7},"8":{"input":{"x":160,"y":120,"connections":[{"id":4,"handleId":"out"}]},"output":{"x":240,"y":220,"connections":[{"handleType":"input","id":6},{"id":7,"handleType":"input"},{"handleType":"input","id":2}]},"id":8},"9":{"input":{"x":240,"y":360,"connections":[]},"output":{"x":340,"y":340,"connections":[{"id":1,"handleId":"in2"}]},"id":9}},"nextId":10}',
	/** A single AND gate */
	singleAnd:
		'{"components":{"0":{"type":"AND","size":{"x":4,"y":4},"position":{"x":360,"y":300},"handles":{"in1":{"edge":"left","pos":1,"type":"input","connections":[]},"in2":{"edge":"left","pos":3,"type":"input","connections":[]},"out":{"edge":"right","pos":2,"type":"output","connections":[]}},"isPoweredInitially":false,"id":0}},"wires":{},"nextId":1}',
	/** A single OR gate */
	singleOR:
		'{"components":{"0":{"type":"OR","size":{"x":4,"y":4},"position":{"x":380,"y":340},"handles":{"in1":{"edge":"left","pos":1,"type":"input","connections":[]},"in2":{"edge":"left","pos":3,"type":"input","connections":[]},"out":{"edge":"right","pos":2,"type":"output","connections":[]}},"isPoweredInitially":false,"id":0}},"wires":{},"nextId":1}',
};
